TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += pace5000.db
DATA += pace5000.proto

#=======================================
include $(TOP)/configure/RULES
